
/* error codes for the typedef error */

#define ERR_NO_ERROR (0) 
#define ERR_DATA_NOT_AN_ELEMENT (10) 
#define ERR_DATA_NOT_A_NODE     (11)
#define ERR_DATA_NOT_A_DOCUMENT (12)
#define ERR_DATA_NOT_A_STRING   (13)
#define ERR_DATA_NOT_A_NODELIST (14)
#define ERR_DATA_NOT_A_COMMENT  (15)
#define ERR_DATA_NOT_AN_ATTR    (16)
#define ERR_DATA_NOT_A_NAMEDNODEMAP (17)
#define ERR_DATA_NOT_A_TEXT         (18)
#define ERR_DATA_NOT_AN_ENTITYREF   (19)
#define ERR_DATA_NOT_AN_ENTITY    (20)
#define ERR_DATA_NOT_A_PROCESSINGINSTRUCTION   (21)
#define ERR_DATA_NOT_A_CDATASECTION   (22)
#define ERR_DATA_NOT_A_DOCUMENTFRAGMENT (23)
#define ERR_DATA_NOT_A_DOCUMENTTYPE    (24)
#define ERR_DATA_NOT_A_DOMIMPLEMENTATION   (25)
#define ERR_DATA_NOT_A_XPATHEVALUATOR   (26)
#define ERR_DATA_NOT_A_XPATHRESULT   (27)
#define ERR_DATA_NOT_A_XPATHNSRESOLVER  (28)
#define ERR_NO_CACHE_HIT        (100) 
#define ERR_NULL_CODE           (101)

#define ERR_NEVER_RETURN_THIS (1000)

#define ERR_GDOME (10000)

