    integer,parameter :: F90XML_LOAD_PARSING = 0
    integer,parameter :: F90XML_LOAD_VALIDATING = 1
    integer,parameter :: F90XML_LOAD_RECOVERING = 2
    integer,parameter :: F90XML_LOAD_SUBSTITUTE_ENTITIES = 4
    integer,parameter :: F90XML_LOAD_COMPLETE_ATTRS = 8

    integer,parameter :: F90XML_SAVE_STANDARD = 0
    integer,parameter :: F90XML_SAVE_LIBXML_INDENT = 1
    integer,parameter :: F90XML_NULLCODE = 0
	integer,parameter :: NullCode = 0

    integer,parameter :: F90XML_ELEMENT_NODE = 1
    integer,parameter :: F90XML_ATTRIBUTE_NODE = 2
    integer,parameter :: F90XML_TEXT_NODE = 3
    integer,parameter :: F90XML_CDATA_SECTION_NODE = 4
    integer,parameter :: F90XML_ENTITY_REFERENCE_NODE = 5
    integer,parameter :: F90XML_ENTITY_NODE = 6
    integer,parameter :: F90XML_PROCESSING_INSTRUCTION_NODE = 7
    integer,parameter :: F90XML_COMMENT_NODE = 8
    integer,parameter :: F90XML_DOCUMENT_NODE = 9
    integer,parameter :: F90XML_DOCUMENT_TYPE_NODE = 10
    integer,parameter :: F90XML_DOCUMENT_FRAGMENT_NODE = 11
    integer,parameter :: F90XML_NOTATION_NODE = 12
    integer,parameter :: F90XML_XPATH_NAMESPACE_NODE = 13

    integer,parameter :: F90XML_ANY_TYPE = 0
    integer,parameter :: F90XML_NUMBER_TYPE = 1
    integer,parameter :: F90XML_STRING_TYPE = 2
    integer,parameter :: F90XML_BOOLEAN_TYPE = 3
  	integer,parameter :: F90XML_UNORDERED_NODE_ITERATOR_TYPE = 4
    integer,parameter :: F90XML_ORDERED_NODE_ITERATOR_TYPE = 5
    integer,parameter :: F90XML_UNORDERED_NODE_SNAPSHOT_TYPE = 6
	integer,parameter :: F90XML_ORDERED_NODE_SNAPSHOT_TYPE = 7
    integer,parameter :: F90XML_ANY_UNORDERED_NODE_TYPE = 8
    integer,parameter :: F90XML_FIRST_ORDERED_NODE_TYPE = 9

