/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */




private void f77xml__el_hasChildNodes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeElement *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getElement(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_el_hasChildNodes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__er_hasChildNodes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeEntityReference *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getEntityReference(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_er_hasChildNodes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__dt_hasChildNodes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeDocumentType *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getDocumentType(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_dt_hasChildNodes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__df_hasChildNodes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeDocumentFragment *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getDocumentFragment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_df_hasChildNodes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__pi_hasChildNodes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeProcessingInstruction *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getProcessingInstruction(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_pi_hasChildNodes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__cd_hasChildNodes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeCharacterData *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getCharacterData(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_cd_hasChildNodes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__not_hasChildNodes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeNotation *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getNotation(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_not_hasChildNodes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__cds_hasChildNodes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeCDATASection *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getCDATASection(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_cds_hasChildNodes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__a_specified(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeAttr *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getAttr(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_a_specified(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__a_hasChildNodes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeAttr *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getAttr(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_a_hasChildNodes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__t_hasChildNodes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeText *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getText(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_t_hasChildNodes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__doc_hasChildNodes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeDocument *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getDocument(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_doc_hasChildNodes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__el_hasAttributes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeElement *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getElement(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_el_hasAttributes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__er_hasAttributes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeEntityReference *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getEntityReference(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_er_hasAttributes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__dt_hasAttributes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeDocumentType *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getDocumentType(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_dt_hasAttributes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__df_hasAttributes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeDocumentFragment *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getDocumentFragment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_df_hasAttributes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__pi_hasAttributes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeProcessingInstruction *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getProcessingInstruction(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_pi_hasAttributes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__cd_hasAttributes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeCharacterData *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getCharacterData(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_cd_hasAttributes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__not_hasAttributes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeNotation *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getNotation(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_not_hasAttributes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__cds_hasAttributes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeCDATASection *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getCDATASection(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_cds_hasAttributes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__a_hasAttributes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeAttr *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getAttr(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_a_hasAttributes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__t_hasAttributes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeText *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getText(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_t_hasAttributes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__doc_hasAttributes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeDocument *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getDocument(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_doc_hasAttributes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__n_hasChildNodes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeNode *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getNode(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_n_hasChildNodes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__n_hasAttributes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeNode *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getNode(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_n_hasAttributes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__c_hasAttributes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeComment *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getComment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_c_hasAttributes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__c_hasChildNodes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeComment *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getComment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_c_hasChildNodes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__ent_hasChildNodes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeEntity *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getEntity(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_ent_hasChildNodes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__ent_hasAttributes(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeEntity *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getEntity(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_ent_hasAttributes(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__xpresult_booleanValue(bool *o_ret,
				code *i_code1,
				error *o_err) {
	/* {{{ OK */
	GdomeXPathResult *obj1;
	GdomeException exc;

	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getXPathResult(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	*o_ret = gdome_xpresult_booleanValue(obj1,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		