/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */




static void f77xml__el_setAttributeNS(code *o_ret,
				code *i_code1,
				code *i_code2,
				code *i_code3,
				code *i_code4,
				error *o_err) { 
	/* {{{ OK */
	GdomeElement *obj1;
	GdomeDOMString *obj2;
	GdomeDOMString *obj3;
	GdomeDOMString *obj4;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;
	*o_ret = NullCode;
	
	obj1 = f77xml_Cache_getElement(cache, *i_code1, o_err);
	if (obj1 == NULL) return;
	
	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	obj3 = f77xml_Cache_getDOMString(cache, *i_code3, o_err);
	if (obj3 == NULL) return;

	obj4 = f77xml_Cache_getDOMString(cache, *i_code4, o_err);
	if (obj4 == NULL) return;

	gdome_el_setAttributeNS(obj1,obj2,obj3,obj4,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */

}

		

static void f77xml__di_createDocumentType(code *o_ret,
			code *i_code1,
			code *i_code2,
			code *i_code3,
			code *i_code4,
			error *o_err) { 
	/* {{{ OK */
	GdomeDocumentType *ret;
	GdomeDOMImplementation *obj1;
	GdomeDOMString *obj2;
	GdomeDOMString *obj3;
	GdomeDOMString *obj4;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;
	*o_ret = NullCode;
	
	obj1 = f77xml_Cache_getDOMImplementation(cache, *i_code1, o_err);
	if (obj1 == NULL) return;
	
	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	obj3 = f77xml_Cache_getDOMString(cache, *i_code3, o_err);
	if (obj3 == NULL) return;

	obj4 = f77xml_Cache_getDOMString(cache, *i_code4, o_err);
	if (obj4 == NULL) return;

	ret = gdome_di_createDocumentType(obj1,obj2,obj3,obj4,&exc);
	
	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addDocumentType(cache, (gpointer)ret);

	/* }}} */

}

		

static void f77xml__di_createDocument(code *o_ret,
			code *i_code1,
			code *i_code2,
			code *i_code3,
			code *i_code4,
			error *o_err) { 
	/* {{{ OK */
	GdomeDocument *ret;
	GdomeDOMImplementation *obj1;
	GdomeDOMString *obj2;
	GdomeDOMString *obj3;
	GdomeDocumentType *obj4;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;
	*o_ret = NullCode;
	
	obj1 = f77xml_Cache_getDOMImplementation(cache, *i_code1, o_err);
	if (obj1 == NULL) return;
	
	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) {
		if (*o_err != ERR_NULL_CODE) return;
		*o_err = ERR_NO_ERROR;
	}

	obj3 = f77xml_Cache_getDOMString(cache, *i_code3, o_err);
	if (obj3 == NULL) return;

	obj4 = f77xml_Cache_getDocumentType(cache, *i_code4, o_err);
	if (obj4 == NULL) {
		if (*o_err != ERR_NULL_CODE) return;
		*o_err = ERR_NO_ERROR;
	}

	ret = gdome_di_createDocument(obj1,obj2,obj3,obj4,&exc);
	
	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addDocument(cache, (gpointer)ret);

	/* }}} */

}

					