/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */




void f77xml__str_equal(bool *o_ret,
			code *i_code,
			StringObj *i_string,
			error *o_err) {

	GdomeDOMString *str;
	GdomeException exc;
	Cache *cache;
	
	cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;
	
	str = f77xml_Cache_getDOMString(cache, *i_code, o_err);
	if (str == NULL) return;

	*o_ret = (strcmp(str->str,i_string->str) ? false : true);
	*o_err = ERR_NO_ERROR;

}

					