/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */




private void f77xml__el_cloneNode(code *o_ret,
				code *i_code1,
				bool *i_bool,
				error *o_err) {

	/* {{{ OK */
	GdomeElement *obj1;
	GdomeNode *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getElement(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_el_cloneNode(obj1,*i_bool,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__n_cloneNode(code *o_ret,
				code *i_code1,
				bool *i_bool,
				error *o_err) {

	/* {{{ OK */
	GdomeNode *obj1;
	GdomeNode *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getNode(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_n_cloneNode(obj1,*i_bool,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__c_cloneNode(code *o_ret,
				code *i_code1,
				bool *i_bool,
				error *o_err) {

	/* {{{ OK */
	GdomeComment *obj1;
	GdomeNode *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getComment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_c_cloneNode(obj1,*i_bool,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__doc_cloneNode(code *o_ret,
				code *i_code1,
				bool *i_bool,
				error *o_err) {

	/* {{{ OK */
	GdomeDocument *obj1;
	GdomeNode *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getDocument(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_doc_cloneNode(obj1,*i_bool,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__t_cloneNode(code *o_ret,
				code *i_code1,
				bool *i_bool,
				error *o_err) {

	/* {{{ OK */
	GdomeText *obj1;
	GdomeNode *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getText(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_t_cloneNode(obj1,*i_bool,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__a_cloneNode(code *o_ret,
				code *i_code1,
				bool *i_bool,
				error *o_err) {

	/* {{{ OK */
	GdomeAttr *obj1;
	GdomeNode *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getAttr(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_a_cloneNode(obj1,*i_bool,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__cds_cloneNode(code *o_ret,
				code *i_code1,
				bool *i_bool,
				error *o_err) {

	/* {{{ OK */
	GdomeCDATASection *obj1;
	GdomeNode *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getCDATASection(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_cds_cloneNode(obj1,*i_bool,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__cd_cloneNode(code *o_ret,
				code *i_code1,
				bool *i_bool,
				error *o_err) {

	/* {{{ OK */
	GdomeCharacterData *obj1;
	GdomeNode *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getCharacterData(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_cd_cloneNode(obj1,*i_bool,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__pi_cloneNode(code *o_ret,
				code *i_code1,
				bool *i_bool,
				error *o_err) {

	/* {{{ OK */
	GdomeProcessingInstruction *obj1;
	GdomeNode *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getProcessingInstruction(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_pi_cloneNode(obj1,*i_bool,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__df_cloneNode(code *o_ret,
				code *i_code1,
				bool *i_bool,
				error *o_err) {

	/* {{{ OK */
	GdomeDocumentFragment *obj1;
	GdomeNode *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getDocumentFragment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_df_cloneNode(obj1,*i_bool,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__not_cloneNode(code *o_ret,
				code *i_code1,
				bool *i_bool,
				error *o_err) {

	/* {{{ OK */
	GdomeNotation *obj1;
	GdomeNode *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getNotation(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_not_cloneNode(obj1,*i_bool,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__dt_cloneNode(code *o_ret,
				code *i_code1,
				bool *i_bool,
				error *o_err) {

	/* {{{ OK */
	GdomeDocumentType *obj1;
	GdomeNode *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getDocumentType(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_dt_cloneNode(obj1,*i_bool,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__ent_cloneNode(code *o_ret,
				code *i_code1,
				bool *i_bool,
				error *o_err) {

	/* {{{ OK */
	GdomeEntity *obj1;
	GdomeNode *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getEntity(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_ent_cloneNode(obj1,*i_bool,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__er_cloneNode(code *o_ret,
				code *i_code1,
				bool *i_bool,
				error *o_err) {

	/* {{{ OK */
	GdomeEntityReference *obj1;
	GdomeNode *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getEntityReference(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_er_cloneNode(obj1,*i_bool,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */

}

		