/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */




private void f77xml__el_hasAttributeNS(bool *o_ret,
				code *i_code1,
				code *i_code2,
				code *i_code3,
				error *o_err) {
	/* {{{ OK */
	GdomeElement *obj1;
	GdomeDOMString *obj2;
	GdomeDOMString *obj3;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getElement(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	obj3 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj3 == NULL) return;

	*o_ret = gdome_el_hasAttributeNS(obj1,obj2,obj3,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		