/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */




private void f77xml__el_canAppend(bool *o_ret,
					code *i_code1,
					code *i_code2,
					error *o_err) {
	/* {{{ OK */
	GdomeElement *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getElement(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	*o_ret = gdome_el_canAppend(obj1,obj2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__er_canAppend(bool *o_ret,
					code *i_code1,
					code *i_code2,
					error *o_err) {
	/* {{{ OK */
	GdomeEntityReference *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getEntityReference(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	*o_ret = gdome_er_canAppend(obj1,obj2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__dt_canAppend(bool *o_ret,
					code *i_code1,
					code *i_code2,
					error *o_err) {
	/* {{{ OK */
	GdomeDocumentType *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getDocumentType(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	*o_ret = gdome_dt_canAppend(obj1,obj2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__df_canAppend(bool *o_ret,
					code *i_code1,
					code *i_code2,
					error *o_err) {
	/* {{{ OK */
	GdomeDocumentFragment *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getDocumentFragment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	*o_ret = gdome_df_canAppend(obj1,obj2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__pi_canAppend(bool *o_ret,
					code *i_code1,
					code *i_code2,
					error *o_err) {
	/* {{{ OK */
	GdomeProcessingInstruction *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getProcessingInstruction(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	*o_ret = gdome_pi_canAppend(obj1,obj2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__cd_canAppend(bool *o_ret,
					code *i_code1,
					code *i_code2,
					error *o_err) {
	/* {{{ OK */
	GdomeCharacterData *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getCharacterData(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	*o_ret = gdome_cd_canAppend(obj1,obj2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__not_canAppend(bool *o_ret,
					code *i_code1,
					code *i_code2,
					error *o_err) {
	/* {{{ OK */
	GdomeNotation *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getNotation(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	*o_ret = gdome_not_canAppend(obj1,obj2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__cds_canAppend(bool *o_ret,
					code *i_code1,
					code *i_code2,
					error *o_err) {
	/* {{{ OK */
	GdomeCDATASection *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getCDATASection(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	*o_ret = gdome_cds_canAppend(obj1,obj2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__a_canAppend(bool *o_ret,
					code *i_code1,
					code *i_code2,
					error *o_err) {
	/* {{{ OK */
	GdomeAttr *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getAttr(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	*o_ret = gdome_a_canAppend(obj1,obj2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__t_canAppend(bool *o_ret,
					code *i_code1,
					code *i_code2,
					error *o_err) {
	/* {{{ OK */
	GdomeText *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getText(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	*o_ret = gdome_t_canAppend(obj1,obj2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__doc_canAppend(bool *o_ret,
					code *i_code1,
					code *i_code2,
					error *o_err) {
	/* {{{ OK */
	GdomeDocument *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getDocument(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	*o_ret = gdome_doc_canAppend(obj1,obj2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__n_canAppend(bool *o_ret,
					code *i_code1,
					code *i_code2,
					error *o_err) {
	/* {{{ OK */
	GdomeNode *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getNode(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	*o_ret = gdome_n_canAppend(obj1,obj2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__c_canAppend(bool *o_ret,
					code *i_code1,
					code *i_code2,
					error *o_err) {
	/* {{{ OK */
	GdomeComment *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getComment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	*o_ret = gdome_c_canAppend(obj1,obj2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		

private void f77xml__ent_canAppend(bool *o_ret,
					code *i_code1,
					code *i_code2,
					error *o_err) {
	/* {{{ OK */
	GdomeEntity *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getEntity(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	*o_ret = gdome_ent_canAppend(obj1,obj2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	
	/* }}} */

}

		