/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */




private void f77xml__nl_item(code *o_ret,
				code *i_code1,
				unsigned int *o_uint1,
				error *o_err) {

	/* {{{ OK */
	Cache *cache;
	GdomeNodeList *obj1;
	GdomeNode *ret;
	GdomeException exc;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getNodeList(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_nl_item(obj1,*o_uint1,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__nnm_item(code *o_ret,
				code *i_code1,
				unsigned int *o_uint1,
				error *o_err) {

	/* {{{ OK */
	Cache *cache;
	GdomeNamedNodeMap *obj1;
	GdomeNode *ret;
	GdomeException exc;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getNamedNodeMap(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_nnm_item(obj1,*o_uint1,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__t_splitText(code *o_ret,
				code *i_code1,
				unsigned int *o_uint1,
				error *o_err) {

	/* {{{ OK */
	Cache *cache;
	GdomeText *obj1;
	GdomeText *ret;
	GdomeException exc;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getText(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_t_splitText(obj1,*o_uint1,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addText(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__cds_splitText(code *o_ret,
				code *i_code1,
				unsigned int *o_uint1,
				error *o_err) {

	/* {{{ OK */
	Cache *cache;
	GdomeCDATASection *obj1;
	GdomeText *ret;
	GdomeException exc;

	cache = f77xml_Cache_instance();
	*o_err = ERR_NEVER_RETURN_THIS;

	obj1 = f77xml_Cache_getCDATASection(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_cds_splitText(obj1,*o_uint1,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addText(cache, (gpointer)ret);

	/* }}} */

}

		