/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */




static void f77xml__di_mkref(code *o_ret,
			error *o_err) { 
	/* {{{ OK */
	GdomeDOMImplementation *di;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;
	*o_ret = NullCode;
	
	di = gdome_di_mkref();
	*o_err = ERR_NO_ERROR;
	*o_ret = f77xml_Cache_addDOMImplementation(cache, (gpointer)di);

	/* }}} */

}

					

static void f77xml__debug_dumpCache(code *o_ret,
			error *o_err) { 
	/* {{{ OK */
	Cache *cache = f77xml_Cache_instance();

	f77xml_Cache_dumpStatus(cache);
	*o_err = ERR_NO_ERROR;
	*o_ret = NullCode;

	/* }}} */

}

					

static void f77xml__Cache_flush(code *o_ret,
			error *o_err) { 
	/* {{{ OK */
	Cache *cache = f77xml_Cache_instance();

	f77xml_Cache_flush(cache);
	*o_err = ERR_NO_ERROR;
	*o_ret = NullCode;

	/* }}} */

}

					

static void f77xml__xpeval_mkref(code *o_ret,
			error *o_err) { 
	/* {{{ OK */
	GdomeXPathEvaluator *eval;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = ERR_NEVER_RETURN_THIS;
	
	eval = gdome_xpeval_mkref();

	*o_err = ERR_NO_ERROR;
	*o_ret = f77xml_Cache_addXPathEvaluator(cache, (gpointer)eval);

	/* }}} */

}

					