/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */




void f77xml__di_createDocFromURI(code *o_ret,
			code *i_di,
			StringObj *i_uri,
			unsigned int *i_mode,
			error *o_err) {

	GdomeDOMImplementation *di;
	GdomeDocument *doc;
	GdomeException exc;
	Cache *cache;
	
	cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;
	*o_ret = NullCode;
	
	di = f77xml_Cache_getDOMImplementation(cache, *i_di, o_err);
	if (di == NULL) return;

	doc = gdome_di_createDocFromURI(di,i_uri->str,*i_mode,&exc);

	if (exc) {
		assert ( doc == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;
	*o_ret = f77xml_Cache_addDocument(cache, (gpointer)doc);

}

					