/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */




private void f77xml__str_new(code *o_ret,
				StringObj *i_string,
				error *o_err) {
	/* {{{ */
	GdomeDOMString *domString;
	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	domString = gdome_str_mkref_dup(i_string->str);

	*o_ret = f77xml_Cache_addDOMString(cache, (gpointer)domString);
	/* }}} */

}

					

private void f77xml__str_mkref(code *o_ret,
				StringObj *i_string,
				error *o_err) {
	/* {{{ */
	GdomeDOMString *domString;
	Cache *cache;

	cache = f77xml_Cache_instance();
	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	domString = gdome_str_mkref_dup(i_string->str);

	*o_ret = f77xml_Cache_addDOMString(cache, (gpointer)domString);
	/* }}} */

}

					