/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */




void f77xml__xpeval_evaluate(code *o_ret,
			code *i_eval,
			code *i_str,
			code *i_node,
			code *i_xpnsresolv,
			unsigned int *i_type,
			code *i_xpres,
			error *o_err) {
	/* {{{ */ 
	GdomeXPathResult *ret;
	GdomeXPathEvaluator *eval;
	GdomeDOMString *str;
	GdomeNode *node;
	GdomeXPathNSResolver *xpnsresolv;
	GdomeXPathResult *xpres;
	GdomeException exc;
	Cache *cache;
	
	cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;
	*o_ret = NullCode;
	
	eval = f77xml_Cache_getXPathEvaluator(cache, *i_eval, o_err);
	if (eval == NULL) return;

	str = f77xml_Cache_getDOMString(cache, *i_str, o_err);
	if (str == NULL) return;

	node = f77xml_Cache_getNode(cache, *i_node, o_err);
	if (node == NULL) return;

	xpnsresolv = f77xml_Cache_getXPathNSResolver(cache, *i_xpnsresolv, o_err);
	if (xpnsresolv == NULL) {
		if (*o_err != ERR_NULL_CODE) return;
		*o_err = ERR_NO_ERROR;
	}

	xpres = f77xml_Cache_getXPathResult(cache, *i_xpres, o_err);
	if (xpres == NULL) {
		if (*o_err != ERR_NULL_CODE) return;
		*o_err = ERR_NO_ERROR;
	}

	ret = gdome_xpeval_evaluate(eval,str,node,xpnsresolv,*i_type,xpres,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addXPathResult(cache, (gpointer)ret);
	
	/* }}} */
		
}

					