/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */




private void f77xml__c_deleteData(code *o_ret,
				code *i_code1,
				unsigned int *o_uint1,
				unsigned int *o_uint2,
				error *o_err) {

	/* {{{ OK */
	GdomeComment *obj1;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;
	*o_ret = NullCode;

	obj1 = f77xml_Cache_getComment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	gdome_c_deleteData(obj1,*o_uint1,*o_uint2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	*o_ret = NullCode;

	/* }}} */

}

		

private void f77xml__t_deleteData(code *o_ret,
				code *i_code1,
				unsigned int *o_uint1,
				unsigned int *o_uint2,
				error *o_err) {

	/* {{{ OK */
	GdomeText *obj1;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;
	*o_ret = NullCode;

	obj1 = f77xml_Cache_getText(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	gdome_t_deleteData(obj1,*o_uint1,*o_uint2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	*o_ret = NullCode;

	/* }}} */

}

		

private void f77xml__cds_deleteData(code *o_ret,
				code *i_code1,
				unsigned int *o_uint1,
				unsigned int *o_uint2,
				error *o_err) {

	/* {{{ OK */
	GdomeCDATASection *obj1;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;
	*o_ret = NullCode;

	obj1 = f77xml_Cache_getCDATASection(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	gdome_cds_deleteData(obj1,*o_uint1,*o_uint2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	*o_ret = NullCode;

	/* }}} */

}

		

private void f77xml__cd_deleteData(code *o_ret,
				code *i_code1,
				unsigned int *o_uint1,
				unsigned int *o_uint2,
				error *o_err) {

	/* {{{ OK */
	GdomeCharacterData *obj1;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;
	*o_ret = NullCode;

	obj1 = f77xml_Cache_getCharacterData(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	gdome_cd_deleteData(obj1,*o_uint1,*o_uint2,&exc);

	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}

	*o_err = ERR_NO_ERROR;
	*o_ret = NullCode;

	/* }}} */

}

		

private void f77xml__c_substringData(code *o_ret,
				code *i_code1,
				unsigned int *o_uint1,
				unsigned int *o_uint2,
				error *o_err) {

	/* {{{ OK */
	GdomeComment *obj1;
	GdomeDOMString *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;
	*o_ret = NullCode;

	obj1 = f77xml_Cache_getComment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_c_substringData(obj1,*o_uint1,*o_uint2,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addDOMString(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__t_substringData(code *o_ret,
				code *i_code1,
				unsigned int *o_uint1,
				unsigned int *o_uint2,
				error *o_err) {

	/* {{{ OK */
	GdomeText *obj1;
	GdomeDOMString *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;
	*o_ret = NullCode;

	obj1 = f77xml_Cache_getText(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_t_substringData(obj1,*o_uint1,*o_uint2,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addDOMString(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__cds_substringData(code *o_ret,
				code *i_code1,
				unsigned int *o_uint1,
				unsigned int *o_uint2,
				error *o_err) {

	/* {{{ OK */
	GdomeCDATASection *obj1;
	GdomeDOMString *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;
	*o_ret = NullCode;

	obj1 = f77xml_Cache_getCDATASection(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_cds_substringData(obj1,*o_uint1,*o_uint2,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addDOMString(cache, (gpointer)ret);

	/* }}} */

}

		

private void f77xml__cd_substringData(code *o_ret,
				code *i_code1,
				unsigned int *o_uint1,
				unsigned int *o_uint2,
				error *o_err) {

	/* {{{ OK */
	GdomeCharacterData *obj1;
	GdomeDOMString *ret;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_err = ERR_NEVER_RETURN_THIS;
	*o_ret = NullCode;

	obj1 = f77xml_Cache_getCharacterData(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	ret = gdome_cd_substringData(obj1,*o_uint1,*o_uint2,&exc);

	if (exc) {
		assert (ret == NULL);
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addDOMString(cache, (gpointer)ret);

	/* }}} */

}

		