/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */




private void f77xml__nnm_getNamedItem(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeNamedNodeMap *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getNamedNodeMap(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_nnm_getNamedItem(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__nnm_setNamedItem(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeNamedNodeMap *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getNamedNodeMap(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_nnm_setNamedItem(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__nnm_setNamedItemNS(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeNamedNodeMap *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getNamedNodeMap(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_nnm_setNamedItemNS(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__nnm_removeNamedItem(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeNamedNodeMap *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getNamedNodeMap(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_nnm_removeNamedItem(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__el_appendChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeElement *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getElement(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_el_appendChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__a_set_value(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeAttr *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getAttr(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_a_set_value(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__doc_createElement(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeElement *ret;
	GdomeDocument *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocument(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_doc_createElement(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addElement(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__doc_createTextNode(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeText *ret;
	GdomeDocument *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocument(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_doc_createTextNode(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addText(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__doc_createComment(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeComment *ret;
	GdomeDocument *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocument(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_doc_createComment(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addComment(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__el_getAttribute(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeDOMString *ret;
	GdomeElement *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getElement(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_el_getAttribute(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addDOMString(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__el_removeAttribute(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeElement *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getElement(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_el_removeAttribute(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__el_getElementsByTagName(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNodeList *ret;
	GdomeElement *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getElement(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_el_getElementsByTagName(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNodeList(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__el_getAttributeNode(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeAttr *ret;
	GdomeElement *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getElement(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_el_getAttributeNode(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addAttr(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__el_setAttributeNode(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeAttr *ret;
	GdomeElement *obj1;
	GdomeAttr *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getElement(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getAttr(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_el_setAttributeNode(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addAttr(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__el_removeAttributeNode(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeAttr *ret;
	GdomeElement *obj1;
	GdomeAttr *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getElement(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getAttr(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_el_removeAttributeNode(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addAttr(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__el_setAttributeNodeNS(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeAttr *ret;
	GdomeElement *obj1;
	GdomeAttr *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getElement(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getAttr(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_el_setAttributeNodeNS(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addAttr(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__el_removeChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeElement *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getElement(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_el_removeChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__er_removeChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeEntityReference *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getEntityReference(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_er_removeChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__dt_removeChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeDocumentType *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocumentType(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_dt_removeChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__df_removeChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeDocumentFragment *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocumentFragment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_df_removeChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__pi_removeChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeProcessingInstruction *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getProcessingInstruction(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_pi_removeChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__cd_removeChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeCharacterData *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getCharacterData(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_cd_removeChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__not_removeChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeNotation *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getNotation(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_not_removeChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__cds_removeChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeCDATASection *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getCDATASection(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_cds_removeChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__doc_removeChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeDocument *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocument(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_doc_removeChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__a_removeChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeAttr *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getAttr(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_a_removeChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__er_set_prefix(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeEntityReference *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getEntityReference(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_er_set_prefix(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__el_set_prefix(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeElement *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getElement(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_el_set_prefix(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__dt_set_prefix(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeDocumentType *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocumentType(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_dt_set_prefix(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__df_set_prefix(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeDocumentFragment *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocumentFragment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_df_set_prefix(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__pi_set_prefix(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeProcessingInstruction *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getProcessingInstruction(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_pi_set_prefix(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__cd_set_prefix(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeCharacterData *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getCharacterData(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_cd_set_prefix(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__not_set_prefix(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNotation *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getNotation(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_not_set_prefix(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__cds_set_prefix(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeCDATASection *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getCDATASection(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_cds_set_prefix(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__a_set_prefix(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeAttr *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getAttr(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_a_set_prefix(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__el_set_nodeValue(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeElement *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getElement(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_el_set_nodeValue(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__er_set_nodeValue(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeEntityReference *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getEntityReference(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_er_set_nodeValue(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__dt_set_nodeValue(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeDocumentType *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocumentType(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_dt_set_nodeValue(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__df_set_nodeValue(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeDocumentFragment *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocumentFragment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_df_set_nodeValue(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__cd_set_nodeValue(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeCharacterData *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getCharacterData(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_cd_set_nodeValue(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__a_set_nodeValue(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeAttr *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getAttr(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_a_set_nodeValue(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__doc_set_nodeValue(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeDocument *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocument(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_doc_set_nodeValue(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__n_appendChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeNode *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getNode(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_n_appendChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__er_appendChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeEntityReference *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getEntityReference(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_er_appendChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__dt_appendChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeDocumentType *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocumentType(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_dt_appendChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__df_appendChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeDocumentFragment *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocumentFragment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_df_appendChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__pi_appendChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeProcessingInstruction *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getProcessingInstruction(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_pi_appendChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__cd_appendChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeCharacterData *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getCharacterData(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_cd_appendChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__not_appendChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeNotation *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getNotation(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_not_appendChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__cds_appendChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeCDATASection *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getCDATASection(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_cds_appendChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__a_appendChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeAttr *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getAttr(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_a_appendChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__doc_appendChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeDocument *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocument(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_doc_appendChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__t_appendChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeText *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getText(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_t_appendChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__n_removeChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeNode *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getNode(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_n_removeChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__t_removeChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeText *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getText(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_t_removeChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__n_set_prefix(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getNode(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_n_set_prefix(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__doc_set_prefix(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeDocument *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocument(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_doc_set_prefix(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__n_set_nodeValue(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getNode(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_n_set_nodeValue(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__not_set_nodeValue(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNotation *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getNotation(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_not_set_nodeValue(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__c_set_data(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeComment *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getComment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_c_set_data(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__pi_set_data(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeProcessingInstruction *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getProcessingInstruction(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_pi_set_data(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__cd_set_data(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeCharacterData *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getCharacterData(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_cd_set_data(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__cds_set_data(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeCDATASection *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getCDATASection(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_cds_set_data(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__t_set_data(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeText *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getText(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_t_set_data(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__c_appendData(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeComment *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getComment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_c_appendData(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__cd_appendData(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeCharacterData *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getCharacterData(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_cd_appendData(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__cds_appendData(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeCDATASection *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getCDATASection(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_cds_appendData(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__t_appendData(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeText *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getText(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_t_appendData(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__c_removeChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeComment *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getComment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_c_removeChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__c_appendChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeComment *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getComment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_c_appendChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__c_set_nodeValue(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeComment *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getComment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_c_set_nodeValue(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__pi_set_nodeValue(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeProcessingInstruction *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getProcessingInstruction(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_pi_set_nodeValue(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__cds_set_nodeValue(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeCDATASection *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getCDATASection(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_cds_set_nodeValue(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__c_set_prefix(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeComment *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getComment(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_c_set_prefix(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__t_set_nodeValue(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeText *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getText(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_t_set_nodeValue(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__t_set_prefix(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeText *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getText(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_t_set_prefix(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__doc_createCDATASection(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeCDATASection *ret;
	GdomeDocument *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocument(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_doc_createCDATASection(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addCDATASection(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__doc_createAttribute(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeAttr *ret;
	GdomeDocument *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocument(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_doc_createAttribute(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addAttr(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__doc_createEntityReference(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeEntityReference *ret;
	GdomeDocument *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocument(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_doc_createEntityReference(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addEntityReference(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__doc_getElementsByTagName(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNodeList *ret;
	GdomeDocument *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocument(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_doc_getElementsByTagName(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNodeList(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__ent_set_nodeValue(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeEntity *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getEntity(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_ent_set_nodeValue(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__ent_removeChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeEntity *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getEntity(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_ent_removeChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__ent_appendChild(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeNode *ret;
	GdomeEntity *obj1;
	GdomeNode *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getEntity(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getNode(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_ent_appendChild(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addNode(cache, (gpointer)ret);

	/* }}} */
}

		

private void f77xml__ent_set_prefix(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeEntity *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getEntity(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	gdome_ent_set_prefix(obj1,obj2,&exc);
	
	if (exc) {
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	/* }}} */
}

		

private void f77xml__doc_getElementById(code *o_ret,
				code *i_code1,
				code *i_code2,
				error *o_err) { 
	/* {{{ OK */
	GdomeElement *ret;
	GdomeDocument *obj1;
	GdomeDOMString *obj2;
	GdomeException exc;

	Cache *cache = f77xml_Cache_instance();

	*o_ret = NullCode;
	*o_err = ERR_NEVER_RETURN_THIS;
	
	obj1 = f77xml_Cache_getDocument(cache, *i_code1, o_err);
	if (obj1 == NULL) return;

	obj2 = f77xml_Cache_getDOMString(cache, *i_code2, o_err);
	if (obj2 == NULL) return;

	ret = gdome_doc_getElementById(obj1,obj2,&exc);
	
	if (exc) {
		assert ( ret == NULL );
		*o_err = ERR_GDOME;
		return;
	}
	
	*o_err = ERR_NO_ERROR;

	if (ret == NULL) {
		*o_ret = NullCode;
		return;
	}

	*o_ret = f77xml_Cache_addElement(cache, (gpointer)ret);

	/* }}} */
}

		