/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */


#include <gdome.h>
#include <gdome-xpath.h>
#include <unistd.h>
#include <assert.h>
#include "mp_p5t3.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p5t3 type functions
 *
 */


struct signatures_p5t3 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(bool *, code *, code *, code *, error *);
};


/* prototypes for handling functions */

private void f77xml__el_hasAttributeNS(bool *, code *, code *, code *, error *);


private struct signatures_p5t3 p5t3Array[] = {
	{"el_hasAttributeNS", &f77xml__el_hasAttributeNS },
	{"", NULL }
};


void f77xml_p5t3_print() {
	struct signatures_p5t3 *signaturePtr;
	signaturePtr=p5t3Array;
	printf("p5t3 (bool *, code *, code *, code *, error *)\n");
	while (signaturePtr->functor) {
		printf("    %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p5t3_multiplexer(bool * ret, StringObj *funcname, code * param0, code * param1, code * param2, error * param3) {
	struct signatures_p5t3 *signaturePtr;
	void (*functorPtr)(bool *, code *, code *, code *, error *);
	signaturePtr=p5t3Array;
#ifdef DEBUG
	printf("p5t3 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1,  param2,  param3);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p5t3 multiplexer undefined.\n",funcname->str);
}

#include "implementation_p5t3.c"

