/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */


#include <gdome.h>
#include <gdome-xpath.h>
#include <unistd.h>
#include <assert.h>
#include "mp_p6t3.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p6t3 type functions
 *
 */


struct signatures_p6t3 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(code *, code *, unsigned int *, unsigned int *, code *, error *);
};


/* prototypes for handling functions */

private void f77xml__c_replaceData(code *, code *, unsigned int *, unsigned int *, code *, error *);
private void f77xml__t_replaceData(code *, code *, unsigned int *, unsigned int *, code *, error *);
private void f77xml__cds_replaceData(code *, code *, unsigned int *, unsigned int *, code *, error *);
private void f77xml__cd_replaceData(code *, code *, unsigned int *, unsigned int *, code *, error *);


private struct signatures_p6t3 p6t3Array[] = {
	{"c_replaceData", &f77xml__c_replaceData },
	{"t_replaceData", &f77xml__t_replaceData },
	{"cds_replaceData", &f77xml__cds_replaceData },
	{"cd_replaceData", &f77xml__cd_replaceData },
	{"", NULL }
};


void f77xml_p6t3_print() {
	struct signatures_p6t3 *signaturePtr;
	signaturePtr=p6t3Array;
	printf("p6t3 (code *, code *, unsigned int *, unsigned int *, code *, error *)\n");
	while (signaturePtr->functor) {
		printf("    %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p6t3_multiplexer(code * ret, StringObj *funcname, code * param0, unsigned int * param1, unsigned int * param2, code * param3, error * param4) {
	struct signatures_p6t3 *signaturePtr;
	void (*functorPtr)(code *, code *, unsigned int *, unsigned int *, code *, error *);
	signaturePtr=p6t3Array;
#ifdef DEBUG
	printf("p6t3 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1,  param2,  param3,  param4);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p6t3 multiplexer undefined.\n",funcname->str);
}

#include "implementation_p6t3.c"

