/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */


#include <gdome.h>
#include <gdome-xpath.h>
#include <unistd.h>
#include <assert.h>
#include "mp_p5t4.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p5t4 type functions
 *
 */


struct signatures_p5t4 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(code *, code *, unsigned int *, unsigned int *, error *);
};


/* prototypes for handling functions */

private void f77xml__c_deleteData(code *, code *, unsigned int *, unsigned int *, error *);
private void f77xml__t_deleteData(code *, code *, unsigned int *, unsigned int *, error *);
private void f77xml__cds_deleteData(code *, code *, unsigned int *, unsigned int *, error *);
private void f77xml__cd_deleteData(code *, code *, unsigned int *, unsigned int *, error *);
private void f77xml__c_substringData(code *, code *, unsigned int *, unsigned int *, error *);
private void f77xml__t_substringData(code *, code *, unsigned int *, unsigned int *, error *);
private void f77xml__cds_substringData(code *, code *, unsigned int *, unsigned int *, error *);
private void f77xml__cd_substringData(code *, code *, unsigned int *, unsigned int *, error *);


private struct signatures_p5t4 p5t4Array[] = {
	{"c_deleteData", &f77xml__c_deleteData },
	{"t_deleteData", &f77xml__t_deleteData },
	{"cds_deleteData", &f77xml__cds_deleteData },
	{"cd_deleteData", &f77xml__cd_deleteData },
	{"c_substringData", &f77xml__c_substringData },
	{"t_substringData", &f77xml__t_substringData },
	{"cds_substringData", &f77xml__cds_substringData },
	{"cd_substringData", &f77xml__cd_substringData },
	{"", NULL }
};


void f77xml_p5t4_print() {
	struct signatures_p5t4 *signaturePtr;
	signaturePtr=p5t4Array;
	printf("p5t4 (code *, code *, unsigned int *, unsigned int *, error *)\n");
	while (signaturePtr->functor) {
		printf("    %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p5t4_multiplexer(code * ret, StringObj *funcname, code * param0, unsigned int * param1, unsigned int * param2, error * param3) {
	struct signatures_p5t4 *signaturePtr;
	void (*functorPtr)(code *, code *, unsigned int *, unsigned int *, error *);
	signaturePtr=p5t4Array;
#ifdef DEBUG
	printf("p5t4 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1,  param2,  param3);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p5t4 multiplexer undefined.\n",funcname->str);
}

#include "implementation_p5t4.c"

