/* automatically generated by APIGen */

#include "stringobj.h"
#include "defines.h"

void f77xml_p5t4_print();
void f77xml_p5t4_multiplexer(code *, StringObj *, code *, unsigned int *, unsigned int *, error *);
