/* automatically generated by APIGen */

#include "stringobj.h"
#include "defines.h"

void f77xml_p6t3_print();
void f77xml_p6t3_multiplexer(code *, StringObj *, code *, unsigned int *, unsigned int *, code *, error *);
