/* automatically generated by APIGen */

#include "stringobj.h"
#include "defines.h"

void f77xml_p5t5_print();
void f77xml_p5t5_multiplexer(code *, StringObj *, code *, StringObj *, unsigned int *, error *);
