/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */


#include <gdome.h>
#include <gdome-xpath.h>
#include <unistd.h>
#include <assert.h>
#include "mp_p3t4.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p3t4 type functions
 *
 */


struct signatures_p3t4 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(bool *, code *, error *);
};


/* prototypes for handling functions */

private void f77xml__el_hasChildNodes(bool *, code *, error *);
private void f77xml__er_hasChildNodes(bool *, code *, error *);
private void f77xml__dt_hasChildNodes(bool *, code *, error *);
private void f77xml__df_hasChildNodes(bool *, code *, error *);
private void f77xml__pi_hasChildNodes(bool *, code *, error *);
private void f77xml__cd_hasChildNodes(bool *, code *, error *);
private void f77xml__not_hasChildNodes(bool *, code *, error *);
private void f77xml__cds_hasChildNodes(bool *, code *, error *);
private void f77xml__a_specified(bool *, code *, error *);
private void f77xml__a_hasChildNodes(bool *, code *, error *);
private void f77xml__t_hasChildNodes(bool *, code *, error *);
private void f77xml__doc_hasChildNodes(bool *, code *, error *);
private void f77xml__el_hasAttributes(bool *, code *, error *);
private void f77xml__er_hasAttributes(bool *, code *, error *);
private void f77xml__dt_hasAttributes(bool *, code *, error *);
private void f77xml__df_hasAttributes(bool *, code *, error *);
private void f77xml__pi_hasAttributes(bool *, code *, error *);
private void f77xml__cd_hasAttributes(bool *, code *, error *);
private void f77xml__not_hasAttributes(bool *, code *, error *);
private void f77xml__cds_hasAttributes(bool *, code *, error *);
private void f77xml__a_hasAttributes(bool *, code *, error *);
private void f77xml__t_hasAttributes(bool *, code *, error *);
private void f77xml__doc_hasAttributes(bool *, code *, error *);
private void f77xml__n_hasChildNodes(bool *, code *, error *);
private void f77xml__n_hasAttributes(bool *, code *, error *);
private void f77xml__c_hasAttributes(bool *, code *, error *);
private void f77xml__c_hasChildNodes(bool *, code *, error *);
private void f77xml__ent_hasChildNodes(bool *, code *, error *);
private void f77xml__ent_hasAttributes(bool *, code *, error *);
private void f77xml__xpresult_booleanValue(bool *, code *, error *);


private struct signatures_p3t4 p3t4Array[] = {
	{"el_hasChildNodes", &f77xml__el_hasChildNodes },
	{"er_hasChildNodes", &f77xml__er_hasChildNodes },
	{"dt_hasChildNodes", &f77xml__dt_hasChildNodes },
	{"df_hasChildNodes", &f77xml__df_hasChildNodes },
	{"pi_hasChildNodes", &f77xml__pi_hasChildNodes },
	{"cd_hasChildNodes", &f77xml__cd_hasChildNodes },
	{"not_hasChildNodes", &f77xml__not_hasChildNodes },
	{"cds_hasChildNodes", &f77xml__cds_hasChildNodes },
	{"a_specified", &f77xml__a_specified },
	{"a_hasChildNodes", &f77xml__a_hasChildNodes },
	{"t_hasChildNodes", &f77xml__t_hasChildNodes },
	{"doc_hasChildNodes", &f77xml__doc_hasChildNodes },
	{"el_hasAttributes", &f77xml__el_hasAttributes },
	{"er_hasAttributes", &f77xml__er_hasAttributes },
	{"dt_hasAttributes", &f77xml__dt_hasAttributes },
	{"df_hasAttributes", &f77xml__df_hasAttributes },
	{"pi_hasAttributes", &f77xml__pi_hasAttributes },
	{"cd_hasAttributes", &f77xml__cd_hasAttributes },
	{"not_hasAttributes", &f77xml__not_hasAttributes },
	{"cds_hasAttributes", &f77xml__cds_hasAttributes },
	{"a_hasAttributes", &f77xml__a_hasAttributes },
	{"t_hasAttributes", &f77xml__t_hasAttributes },
	{"doc_hasAttributes", &f77xml__doc_hasAttributes },
	{"n_hasChildNodes", &f77xml__n_hasChildNodes },
	{"n_hasAttributes", &f77xml__n_hasAttributes },
	{"c_hasAttributes", &f77xml__c_hasAttributes },
	{"c_hasChildNodes", &f77xml__c_hasChildNodes },
	{"ent_hasChildNodes", &f77xml__ent_hasChildNodes },
	{"ent_hasAttributes", &f77xml__ent_hasAttributes },
	{"xpresult_booleanValue", &f77xml__xpresult_booleanValue },
	{"", NULL }
};


void f77xml_p3t4_print() {
	struct signatures_p3t4 *signaturePtr;
	signaturePtr=p3t4Array;
	printf("p3t4 (bool *, code *, error *)\n");
	while (signaturePtr->functor) {
		printf("    %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p3t4_multiplexer(bool * ret, StringObj *funcname, code * param0, error * param1) {
	struct signatures_p3t4 *signaturePtr;
	void (*functorPtr)(bool *, code *, error *);
	signaturePtr=p3t4Array;
#ifdef DEBUG
	printf("p3t4 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p3t4 multiplexer undefined.\n",funcname->str);
}

#include "implementation_p3t4.c"

