/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */


#include <gdome.h>
#include <gdome-xpath.h>
#include <unistd.h>
#include <assert.h>
#include "mp_p5t6.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p5t6 type functions
 *
 */


struct signatures_p5t6 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(code *, code *, unsigned int *, code *, error *);
};


/* prototypes for handling functions */

private void f77xml__c_insertData(code *, code *, unsigned int *, code *, error *);
private void f77xml__t_insertData(code *, code *, unsigned int *, code *, error *);
private void f77xml__cds_insertData(code *, code *, unsigned int *, code *, error *);
private void f77xml__cd_insertData(code *, code *, unsigned int *, code *, error *);


private struct signatures_p5t6 p5t6Array[] = {
	{"c_insertData", &f77xml__c_insertData },
	{"t_insertData", &f77xml__t_insertData },
	{"cds_insertData", &f77xml__cds_insertData },
	{"cd_insertData", &f77xml__cd_insertData },
	{"", NULL }
};


void f77xml_p5t6_print() {
	struct signatures_p5t6 *signaturePtr;
	signaturePtr=p5t6Array;
	printf("p5t6 (code *, code *, unsigned int *, code *, error *)\n");
	while (signaturePtr->functor) {
		printf("    %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p5t6_multiplexer(code * ret, StringObj *funcname, code * param0, unsigned int * param1, code * param2, error * param3) {
	struct signatures_p5t6 *signaturePtr;
	void (*functorPtr)(code *, code *, unsigned int *, code *, error *);
	signaturePtr=p5t6Array;
#ifdef DEBUG
	printf("p5t6 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1,  param2,  param3);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p5t6 multiplexer undefined.\n",funcname->str);
}

#include "implementation_p5t6.c"

