/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */


#include <gdome.h>
#include <gdome-xpath.h>
#include <unistd.h>
#include <assert.h>
#include "mp_p6t1.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p6t1 type functions
 *
 */


struct signatures_p6t1 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(code *, code *, code *, code *, code *, error *);
};


/* prototypes for handling functions */

private void f77xml__el_setAttributeNS(code *, code *, code *, code *, code *, error *);
private void f77xml__di_createDocumentType(code *, code *, code *, code *, code *, error *);
private void f77xml__di_createDocument(code *, code *, code *, code *, code *, error *);


private struct signatures_p6t1 p6t1Array[] = {
	{"el_setAttributeNS", &f77xml__el_setAttributeNS },
	{"di_createDocumentType", &f77xml__di_createDocumentType },
	{"di_createDocument", &f77xml__di_createDocument },
	{"", NULL }
};


void f77xml_p6t1_print() {
	struct signatures_p6t1 *signaturePtr;
	signaturePtr=p6t1Array;
	printf("p6t1 (code *, code *, code *, code *, code *, error *)\n");
	while (signaturePtr->functor) {
		printf("    %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p6t1_multiplexer(code * ret, StringObj *funcname, code * param0, code * param1, code * param2, code * param3, error * param4) {
	struct signatures_p6t1 *signaturePtr;
	void (*functorPtr)(code *, code *, code *, code *, code *, error *);
	signaturePtr=p6t1Array;
#ifdef DEBUG
	printf("p6t1 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1,  param2,  param3,  param4);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p6t1 multiplexer undefined.\n",funcname->str);
}

#include "implementation_p6t1.c"

