/* automatically generated by APIGen */

#include "stringobj.h"
#include "defines.h"

void f77xml_p5t2_print();
void f77xml_p5t2_multiplexer(bool *, StringObj *, code *, StringObj *, unsigned int *, error *);
