/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */


#include <gdome.h>
#include <gdome-xpath.h>
#include <unistd.h>
#include <assert.h>
#include "mp_p4t3.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p4t3 type functions
 *
 */


struct signatures_p4t3 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(bool *, code *, code *, error *);
};


/* prototypes for handling functions */

private void f77xml__el_canAppend(bool *, code *, code *, error *);
private void f77xml__er_canAppend(bool *, code *, code *, error *);
private void f77xml__dt_canAppend(bool *, code *, code *, error *);
private void f77xml__df_canAppend(bool *, code *, code *, error *);
private void f77xml__pi_canAppend(bool *, code *, code *, error *);
private void f77xml__cd_canAppend(bool *, code *, code *, error *);
private void f77xml__not_canAppend(bool *, code *, code *, error *);
private void f77xml__cds_canAppend(bool *, code *, code *, error *);
private void f77xml__a_canAppend(bool *, code *, code *, error *);
private void f77xml__t_canAppend(bool *, code *, code *, error *);
private void f77xml__doc_canAppend(bool *, code *, code *, error *);
private void f77xml__n_canAppend(bool *, code *, code *, error *);
private void f77xml__c_canAppend(bool *, code *, code *, error *);
private void f77xml__ent_canAppend(bool *, code *, code *, error *);


private struct signatures_p4t3 p4t3Array[] = {
	{"el_canAppend", &f77xml__el_canAppend },
	{"er_canAppend", &f77xml__er_canAppend },
	{"dt_canAppend", &f77xml__dt_canAppend },
	{"df_canAppend", &f77xml__df_canAppend },
	{"pi_canAppend", &f77xml__pi_canAppend },
	{"cd_canAppend", &f77xml__cd_canAppend },
	{"not_canAppend", &f77xml__not_canAppend },
	{"cds_canAppend", &f77xml__cds_canAppend },
	{"a_canAppend", &f77xml__a_canAppend },
	{"t_canAppend", &f77xml__t_canAppend },
	{"doc_canAppend", &f77xml__doc_canAppend },
	{"n_canAppend", &f77xml__n_canAppend },
	{"c_canAppend", &f77xml__c_canAppend },
	{"ent_canAppend", &f77xml__ent_canAppend },
	{"", NULL }
};


void f77xml_p4t3_print() {
	struct signatures_p4t3 *signaturePtr;
	signaturePtr=p4t3Array;
	printf("p4t3 (bool *, code *, code *, error *)\n");
	while (signaturePtr->functor) {
		printf("    %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p4t3_multiplexer(bool * ret, StringObj *funcname, code * param0, code * param1, error * param2) {
	struct signatures_p4t3 *signaturePtr;
	void (*functorPtr)(bool *, code *, code *, error *);
	signaturePtr=p4t3Array;
#ifdef DEBUG
	printf("p4t3 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1,  param2);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p4t3 multiplexer undefined.\n",funcname->str);
}

#include "implementation_p4t3.c"

