/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */


#include <gdome.h>
#include <gdome-xpath.h>
#include <unistd.h>
#include <assert.h>
#include "mp_p5t1.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p5t1 type functions
 *
 */


struct signatures_p5t1 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(code *, code *, code *, code *, error *);
};


/* prototypes for handling functions */

private void f77xml__nnm_getNamedItemNS(code *, code *, code *, code *, error *);
private void f77xml__nnm_removeNamedItemNS(code *, code *, code *, code *, error *);
private void f77xml__el_setAttribute(code *, code *, code *, code *, error *);
private void f77xml__doc_createElementNS(code *, code *, code *, code *, error *);
private void f77xml__doc_createAttributeNS(code *, code *, code *, code *, error *);
private void f77xml__doc_getElementsByTagNameNS(code *, code *, code *, code *, error *);
private void f77xml__el_getAttributeNS(code *, code *, code *, code *, error *);
private void f77xml__el_getAttributeNodeNS(code *, code *, code *, code *, error *);
private void f77xml__el_getElementsByTagNameNS(code *, code *, code *, code *, error *);
private void f77xml__el_insertBefore(code *, code *, code *, code *, error *);
private void f77xml__er_insertBefore(code *, code *, code *, code *, error *);
private void f77xml__dt_insertBefore(code *, code *, code *, code *, error *);
private void f77xml__df_insertBefore(code *, code *, code *, code *, error *);
private void f77xml__pi_insertBefore(code *, code *, code *, code *, error *);
private void f77xml__cd_insertBefore(code *, code *, code *, code *, error *);
private void f77xml__not_insertBefore(code *, code *, code *, code *, error *);
private void f77xml__el_replaceChild(code *, code *, code *, code *, error *);
private void f77xml__er_replaceChild(code *, code *, code *, code *, error *);
private void f77xml__dt_replaceChild(code *, code *, code *, code *, error *);
private void f77xml__df_replaceChild(code *, code *, code *, code *, error *);
private void f77xml__pi_replaceChild(code *, code *, code *, code *, error *);
private void f77xml__cd_replaceChild(code *, code *, code *, code *, error *);
private void f77xml__not_replaceChild(code *, code *, code *, code *, error *);
private void f77xml__cds_insertBefore(code *, code *, code *, code *, error *);
private void f77xml__cds_replaceChild(code *, code *, code *, code *, error *);
private void f77xml__t_insertBefore(code *, code *, code *, code *, error *);
private void f77xml__t_replaceChild(code *, code *, code *, code *, error *);
private void f77xml__doc_insertBefore(code *, code *, code *, code *, error *);
private void f77xml__doc_replaceChild(code *, code *, code *, code *, error *);
private void f77xml__n_insertBefore(code *, code *, code *, code *, error *);
private void f77xml__n_replaceChild(code *, code *, code *, code *, error *);
private void f77xml__c_insertBefore(code *, code *, code *, code *, error *);
private void f77xml__c_replaceChild(code *, code *, code *, code *, error *);
private void f77xml__doc_createProcessingInstruction(code *, code *, code *, code *, error *);
private void f77xml__ent_insertBefore(code *, code *, code *, code *, error *);
private void f77xml__ent_replaceChild(code *, code *, code *, code *, error *);
private void f77xml__a_insertBefore(code *, code *, code *, code *, error *);
private void f77xml__a_replaceChild(code *, code *, code *, code *, error *);
private void f77xml__el_removeAttributeNS(code *, code *, code *, code *, error *);


private struct signatures_p5t1 p5t1Array[] = {
	{"nnm_getNamedItemNS", &f77xml__nnm_getNamedItemNS },
	{"nnm_removeNamedItemNS", &f77xml__nnm_removeNamedItemNS },
	{"el_setAttribute", &f77xml__el_setAttribute },
	{"doc_createElementNS", &f77xml__doc_createElementNS },
	{"doc_createAttributeNS", &f77xml__doc_createAttributeNS },
	{"doc_getElementsByTagNameNS", &f77xml__doc_getElementsByTagNameNS },
	{"el_getAttributeNS", &f77xml__el_getAttributeNS },
	{"el_getAttributeNodeNS", &f77xml__el_getAttributeNodeNS },
	{"el_getElementsByTagNameNS", &f77xml__el_getElementsByTagNameNS },
	{"el_insertBefore", &f77xml__el_insertBefore },
	{"er_insertBefore", &f77xml__er_insertBefore },
	{"dt_insertBefore", &f77xml__dt_insertBefore },
	{"df_insertBefore", &f77xml__df_insertBefore },
	{"pi_insertBefore", &f77xml__pi_insertBefore },
	{"cd_insertBefore", &f77xml__cd_insertBefore },
	{"not_insertBefore", &f77xml__not_insertBefore },
	{"el_replaceChild", &f77xml__el_replaceChild },
	{"er_replaceChild", &f77xml__er_replaceChild },
	{"dt_replaceChild", &f77xml__dt_replaceChild },
	{"df_replaceChild", &f77xml__df_replaceChild },
	{"pi_replaceChild", &f77xml__pi_replaceChild },
	{"cd_replaceChild", &f77xml__cd_replaceChild },
	{"not_replaceChild", &f77xml__not_replaceChild },
	{"cds_insertBefore", &f77xml__cds_insertBefore },
	{"cds_replaceChild", &f77xml__cds_replaceChild },
	{"t_insertBefore", &f77xml__t_insertBefore },
	{"t_replaceChild", &f77xml__t_replaceChild },
	{"doc_insertBefore", &f77xml__doc_insertBefore },
	{"doc_replaceChild", &f77xml__doc_replaceChild },
	{"n_insertBefore", &f77xml__n_insertBefore },
	{"n_replaceChild", &f77xml__n_replaceChild },
	{"c_insertBefore", &f77xml__c_insertBefore },
	{"c_replaceChild", &f77xml__c_replaceChild },
	{"doc_createProcessingInstruction", &f77xml__doc_createProcessingInstruction },
	{"ent_insertBefore", &f77xml__ent_insertBefore },
	{"ent_replaceChild", &f77xml__ent_replaceChild },
	{"a_insertBefore", &f77xml__a_insertBefore },
	{"a_replaceChild", &f77xml__a_replaceChild },
	{"el_removeAttributeNS", &f77xml__el_removeAttributeNS },
	{"", NULL }
};


void f77xml_p5t1_print() {
	struct signatures_p5t1 *signaturePtr;
	signaturePtr=p5t1Array;
	printf("p5t1 (code *, code *, code *, code *, error *)\n");
	while (signaturePtr->functor) {
		printf("    %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p5t1_multiplexer(code * ret, StringObj *funcname, code * param0, code * param1, code * param2, error * param3) {
	struct signatures_p5t1 *signaturePtr;
	void (*functorPtr)(code *, code *, code *, code *, error *);
	signaturePtr=p5t1Array;
#ifdef DEBUG
	printf("p5t1 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1,  param2,  param3);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p5t1 multiplexer undefined.\n",funcname->str);
}

#include "implementation_p5t1.c"

