/* automatically generated by APIGen */

#include "stringobj.h"
#include "defines.h"

void f77xml_p8t1_print();
void f77xml_p8t1_multiplexer(code *, StringObj *, code *, code *, code *, code *, unsigned int *, code *, error *);
