/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */


#include <gdome.h>
#include <gdome-xpath.h>
#include <unistd.h>
#include <assert.h>
#include "mp_p3t3.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p3t3 type functions
 *
 */


struct signatures_p3t3 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(unsigned int *, code *, error *);
};


/* prototypes for handling functions */

private void f77xml__str_len(unsigned int *, code *, error *);
private void f77xml__str_length(unsigned int *, code *, error *);
private void f77xml__nl_length(unsigned int *, code *, error *);
private void f77xml__nnm_length(unsigned int *, code *, error *);
private void f77xml__n_nodeType(unsigned int *, code *, error *);
private void f77xml__er_nodeType(unsigned int *, code *, error *);
private void f77xml__dt_nodeType(unsigned int *, code *, error *);
private void f77xml__df_nodeType(unsigned int *, code *, error *);
private void f77xml__pi_nodeType(unsigned int *, code *, error *);
private void f77xml__cd_nodeType(unsigned int *, code *, error *);
private void f77xml__not_nodeType(unsigned int *, code *, error *);
private void f77xml__cds_nodeType(unsigned int *, code *, error *);
private void f77xml__a_nodeType(unsigned int *, code *, error *);
private void f77xml__t_nodeType(unsigned int *, code *, error *);
private void f77xml__el_nodeType(unsigned int *, code *, error *);
private void f77xml__c_nodeType(unsigned int *, code *, error *);
private void f77xml__ent_nodeType(unsigned int *, code *, error *);
private void f77xml__doc_nodeType(unsigned int *, code *, error *);
private void f77xml__c_length(unsigned int *, code *, error *);
private void f77xml__t_length(unsigned int *, code *, error *);
private void f77xml__cds_length(unsigned int *, code *, error *);
private void f77xml__cd_length(unsigned int *, code *, error *);
private void f77xml__xpresult_resultType(unsigned int *, code *, error *);


private struct signatures_p3t3 p3t3Array[] = {
	{"str_len", &f77xml__str_len },
	{"str_length", &f77xml__str_length },
	{"nl_length", &f77xml__nl_length },
	{"nnm_length", &f77xml__nnm_length },
	{"n_nodeType", &f77xml__n_nodeType },
	{"er_nodeType", &f77xml__er_nodeType },
	{"dt_nodeType", &f77xml__dt_nodeType },
	{"df_nodeType", &f77xml__df_nodeType },
	{"pi_nodeType", &f77xml__pi_nodeType },
	{"cd_nodeType", &f77xml__cd_nodeType },
	{"not_nodeType", &f77xml__not_nodeType },
	{"cds_nodeType", &f77xml__cds_nodeType },
	{"a_nodeType", &f77xml__a_nodeType },
	{"t_nodeType", &f77xml__t_nodeType },
	{"el_nodeType", &f77xml__el_nodeType },
	{"c_nodeType", &f77xml__c_nodeType },
	{"ent_nodeType", &f77xml__ent_nodeType },
	{"doc_nodeType", &f77xml__doc_nodeType },
	{"c_length", &f77xml__c_length },
	{"t_length", &f77xml__t_length },
	{"cds_length", &f77xml__cds_length },
	{"cd_length", &f77xml__cd_length },
	{"xpresult_resultType", &f77xml__xpresult_resultType },
	{"", NULL }
};


void f77xml_p3t3_print() {
	struct signatures_p3t3 *signaturePtr;
	signaturePtr=p3t3Array;
	printf("p3t3 (unsigned int *, code *, error *)\n");
	while (signaturePtr->functor) {
		printf("    %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p3t3_multiplexer(unsigned int * ret, StringObj *funcname, code * param0, error * param1) {
	struct signatures_p3t3 *signaturePtr;
	void (*functorPtr)(unsigned int *, code *, error *);
	signaturePtr=p3t3Array;
#ifdef DEBUG
	printf("p3t3 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p3t3 multiplexer undefined.\n",funcname->str);
}

#include "implementation_p3t3.c"

