/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */


#include <gdome.h>
#include <gdome-xpath.h>
#include <unistd.h>
#include <assert.h>
#include "mp_p4t1.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p4t1 type functions
 *
 */


struct signatures_p4t1 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(code *, code *, code *, error *);
};


/* prototypes for handling functions */

private void f77xml__nnm_getNamedItem(code *, code *, code *, error *);
private void f77xml__nnm_setNamedItem(code *, code *, code *, error *);
private void f77xml__nnm_setNamedItemNS(code *, code *, code *, error *);
private void f77xml__nnm_removeNamedItem(code *, code *, code *, error *);
private void f77xml__el_appendChild(code *, code *, code *, error *);
private void f77xml__a_set_value(code *, code *, code *, error *);
private void f77xml__doc_createElement(code *, code *, code *, error *);
private void f77xml__doc_createTextNode(code *, code *, code *, error *);
private void f77xml__doc_createComment(code *, code *, code *, error *);
private void f77xml__el_getAttribute(code *, code *, code *, error *);
private void f77xml__el_removeAttribute(code *, code *, code *, error *);
private void f77xml__el_getElementsByTagName(code *, code *, code *, error *);
private void f77xml__el_getAttributeNode(code *, code *, code *, error *);
private void f77xml__el_setAttributeNode(code *, code *, code *, error *);
private void f77xml__el_removeAttributeNode(code *, code *, code *, error *);
private void f77xml__el_setAttributeNodeNS(code *, code *, code *, error *);
private void f77xml__el_removeChild(code *, code *, code *, error *);
private void f77xml__er_removeChild(code *, code *, code *, error *);
private void f77xml__dt_removeChild(code *, code *, code *, error *);
private void f77xml__df_removeChild(code *, code *, code *, error *);
private void f77xml__pi_removeChild(code *, code *, code *, error *);
private void f77xml__cd_removeChild(code *, code *, code *, error *);
private void f77xml__not_removeChild(code *, code *, code *, error *);
private void f77xml__cds_removeChild(code *, code *, code *, error *);
private void f77xml__doc_removeChild(code *, code *, code *, error *);
private void f77xml__a_removeChild(code *, code *, code *, error *);
private void f77xml__er_set_prefix(code *, code *, code *, error *);
private void f77xml__el_set_prefix(code *, code *, code *, error *);
private void f77xml__dt_set_prefix(code *, code *, code *, error *);
private void f77xml__df_set_prefix(code *, code *, code *, error *);
private void f77xml__pi_set_prefix(code *, code *, code *, error *);
private void f77xml__cd_set_prefix(code *, code *, code *, error *);
private void f77xml__not_set_prefix(code *, code *, code *, error *);
private void f77xml__cds_set_prefix(code *, code *, code *, error *);
private void f77xml__a_set_prefix(code *, code *, code *, error *);
private void f77xml__el_set_nodeValue(code *, code *, code *, error *);
private void f77xml__er_set_nodeValue(code *, code *, code *, error *);
private void f77xml__dt_set_nodeValue(code *, code *, code *, error *);
private void f77xml__df_set_nodeValue(code *, code *, code *, error *);
private void f77xml__cd_set_nodeValue(code *, code *, code *, error *);
private void f77xml__a_set_nodeValue(code *, code *, code *, error *);
private void f77xml__doc_set_nodeValue(code *, code *, code *, error *);
private void f77xml__n_appendChild(code *, code *, code *, error *);
private void f77xml__er_appendChild(code *, code *, code *, error *);
private void f77xml__dt_appendChild(code *, code *, code *, error *);
private void f77xml__df_appendChild(code *, code *, code *, error *);
private void f77xml__pi_appendChild(code *, code *, code *, error *);
private void f77xml__cd_appendChild(code *, code *, code *, error *);
private void f77xml__not_appendChild(code *, code *, code *, error *);
private void f77xml__cds_appendChild(code *, code *, code *, error *);
private void f77xml__a_appendChild(code *, code *, code *, error *);
private void f77xml__doc_appendChild(code *, code *, code *, error *);
private void f77xml__t_appendChild(code *, code *, code *, error *);
private void f77xml__n_removeChild(code *, code *, code *, error *);
private void f77xml__t_removeChild(code *, code *, code *, error *);
private void f77xml__n_set_prefix(code *, code *, code *, error *);
private void f77xml__doc_set_prefix(code *, code *, code *, error *);
private void f77xml__n_set_nodeValue(code *, code *, code *, error *);
private void f77xml__not_set_nodeValue(code *, code *, code *, error *);
private void f77xml__c_set_data(code *, code *, code *, error *);
private void f77xml__pi_set_data(code *, code *, code *, error *);
private void f77xml__cd_set_data(code *, code *, code *, error *);
private void f77xml__cds_set_data(code *, code *, code *, error *);
private void f77xml__t_set_data(code *, code *, code *, error *);
private void f77xml__c_appendData(code *, code *, code *, error *);
private void f77xml__cd_appendData(code *, code *, code *, error *);
private void f77xml__cds_appendData(code *, code *, code *, error *);
private void f77xml__t_appendData(code *, code *, code *, error *);
private void f77xml__c_removeChild(code *, code *, code *, error *);
private void f77xml__c_appendChild(code *, code *, code *, error *);
private void f77xml__c_set_nodeValue(code *, code *, code *, error *);
private void f77xml__pi_set_nodeValue(code *, code *, code *, error *);
private void f77xml__cds_set_nodeValue(code *, code *, code *, error *);
private void f77xml__c_set_prefix(code *, code *, code *, error *);
private void f77xml__t_set_nodeValue(code *, code *, code *, error *);
private void f77xml__t_set_prefix(code *, code *, code *, error *);
private void f77xml__doc_createCDATASection(code *, code *, code *, error *);
private void f77xml__doc_createAttribute(code *, code *, code *, error *);
private void f77xml__doc_createEntityReference(code *, code *, code *, error *);
private void f77xml__doc_getElementsByTagName(code *, code *, code *, error *);
private void f77xml__ent_set_nodeValue(code *, code *, code *, error *);
private void f77xml__ent_removeChild(code *, code *, code *, error *);
private void f77xml__ent_appendChild(code *, code *, code *, error *);
private void f77xml__ent_set_prefix(code *, code *, code *, error *);
private void f77xml__doc_getElementById(code *, code *, code *, error *);


private struct signatures_p4t1 p4t1Array[] = {
	{"nnm_getNamedItem", &f77xml__nnm_getNamedItem },
	{"nnm_setNamedItem", &f77xml__nnm_setNamedItem },
	{"nnm_setNamedItemNS", &f77xml__nnm_setNamedItemNS },
	{"nnm_removeNamedItem", &f77xml__nnm_removeNamedItem },
	{"el_appendChild", &f77xml__el_appendChild },
	{"a_set_value", &f77xml__a_set_value },
	{"doc_createElement", &f77xml__doc_createElement },
	{"doc_createTextNode", &f77xml__doc_createTextNode },
	{"doc_createComment", &f77xml__doc_createComment },
	{"el_getAttribute", &f77xml__el_getAttribute },
	{"el_removeAttribute", &f77xml__el_removeAttribute },
	{"el_getElementsByTagName", &f77xml__el_getElementsByTagName },
	{"el_getAttributeNode", &f77xml__el_getAttributeNode },
	{"el_setAttributeNode", &f77xml__el_setAttributeNode },
	{"el_removeAttributeNode", &f77xml__el_removeAttributeNode },
	{"el_setAttributeNodeNS", &f77xml__el_setAttributeNodeNS },
	{"el_removeChild", &f77xml__el_removeChild },
	{"er_removeChild", &f77xml__er_removeChild },
	{"dt_removeChild", &f77xml__dt_removeChild },
	{"df_removeChild", &f77xml__df_removeChild },
	{"pi_removeChild", &f77xml__pi_removeChild },
	{"cd_removeChild", &f77xml__cd_removeChild },
	{"not_removeChild", &f77xml__not_removeChild },
	{"cds_removeChild", &f77xml__cds_removeChild },
	{"doc_removeChild", &f77xml__doc_removeChild },
	{"a_removeChild", &f77xml__a_removeChild },
	{"er_set_prefix", &f77xml__er_set_prefix },
	{"el_set_prefix", &f77xml__el_set_prefix },
	{"dt_set_prefix", &f77xml__dt_set_prefix },
	{"df_set_prefix", &f77xml__df_set_prefix },
	{"pi_set_prefix", &f77xml__pi_set_prefix },
	{"cd_set_prefix", &f77xml__cd_set_prefix },
	{"not_set_prefix", &f77xml__not_set_prefix },
	{"cds_set_prefix", &f77xml__cds_set_prefix },
	{"a_set_prefix", &f77xml__a_set_prefix },
	{"el_set_nodeValue", &f77xml__el_set_nodeValue },
	{"er_set_nodeValue", &f77xml__er_set_nodeValue },
	{"dt_set_nodeValue", &f77xml__dt_set_nodeValue },
	{"df_set_nodeValue", &f77xml__df_set_nodeValue },
	{"cd_set_nodeValue", &f77xml__cd_set_nodeValue },
	{"a_set_nodeValue", &f77xml__a_set_nodeValue },
	{"doc_set_nodeValue", &f77xml__doc_set_nodeValue },
	{"n_appendChild", &f77xml__n_appendChild },
	{"er_appendChild", &f77xml__er_appendChild },
	{"dt_appendChild", &f77xml__dt_appendChild },
	{"df_appendChild", &f77xml__df_appendChild },
	{"pi_appendChild", &f77xml__pi_appendChild },
	{"cd_appendChild", &f77xml__cd_appendChild },
	{"not_appendChild", &f77xml__not_appendChild },
	{"cds_appendChild", &f77xml__cds_appendChild },
	{"a_appendChild", &f77xml__a_appendChild },
	{"doc_appendChild", &f77xml__doc_appendChild },
	{"t_appendChild", &f77xml__t_appendChild },
	{"n_removeChild", &f77xml__n_removeChild },
	{"t_removeChild", &f77xml__t_removeChild },
	{"n_set_prefix", &f77xml__n_set_prefix },
	{"doc_set_prefix", &f77xml__doc_set_prefix },
	{"n_set_nodeValue", &f77xml__n_set_nodeValue },
	{"not_set_nodeValue", &f77xml__not_set_nodeValue },
	{"c_set_data", &f77xml__c_set_data },
	{"pi_set_data", &f77xml__pi_set_data },
	{"cd_set_data", &f77xml__cd_set_data },
	{"cds_set_data", &f77xml__cds_set_data },
	{"t_set_data", &f77xml__t_set_data },
	{"c_appendData", &f77xml__c_appendData },
	{"cd_appendData", &f77xml__cd_appendData },
	{"cds_appendData", &f77xml__cds_appendData },
	{"t_appendData", &f77xml__t_appendData },
	{"c_removeChild", &f77xml__c_removeChild },
	{"c_appendChild", &f77xml__c_appendChild },
	{"c_set_nodeValue", &f77xml__c_set_nodeValue },
	{"pi_set_nodeValue", &f77xml__pi_set_nodeValue },
	{"cds_set_nodeValue", &f77xml__cds_set_nodeValue },
	{"c_set_prefix", &f77xml__c_set_prefix },
	{"t_set_nodeValue", &f77xml__t_set_nodeValue },
	{"t_set_prefix", &f77xml__t_set_prefix },
	{"doc_createCDATASection", &f77xml__doc_createCDATASection },
	{"doc_createAttribute", &f77xml__doc_createAttribute },
	{"doc_createEntityReference", &f77xml__doc_createEntityReference },
	{"doc_getElementsByTagName", &f77xml__doc_getElementsByTagName },
	{"ent_set_nodeValue", &f77xml__ent_set_nodeValue },
	{"ent_removeChild", &f77xml__ent_removeChild },
	{"ent_appendChild", &f77xml__ent_appendChild },
	{"ent_set_prefix", &f77xml__ent_set_prefix },
	{"doc_getElementById", &f77xml__doc_getElementById },
	{"", NULL }
};


void f77xml_p4t1_print() {
	struct signatures_p4t1 *signaturePtr;
	signaturePtr=p4t1Array;
	printf("p4t1 (code *, code *, code *, error *)\n");
	while (signaturePtr->functor) {
		printf("    %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p4t1_multiplexer(code * ret, StringObj *funcname, code * param0, code * param1, error * param2) {
	struct signatures_p4t1 *signaturePtr;
	void (*functorPtr)(code *, code *, code *, error *);
	signaturePtr=p4t1Array;
#ifdef DEBUG
	printf("p4t1 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1,  param2);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p4t1 multiplexer undefined.\n",funcname->str);
}

#include "implementation_p4t1.c"

