/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */


#include <gdome.h>
#include <gdome-xpath.h>
#include <unistd.h>
#include <assert.h>
#include "mp_p6t2.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p6t2 type functions
 *
 */


struct signatures_p6t2 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(bool *, code *, code *, StringObj *, unsigned int *, error *);
};


/* prototypes for handling functions */

private void f77xml__di_saveDocToFile(bool *, code *, code *, StringObj *, unsigned int *, error *);


private struct signatures_p6t2 p6t2Array[] = {
	{"di_saveDocToFile", &f77xml__di_saveDocToFile },
	{"", NULL }
};


void f77xml_p6t2_print() {
	struct signatures_p6t2 *signaturePtr;
	signaturePtr=p6t2Array;
	printf("p6t2 (bool *, code *, code *, StringObj *, unsigned int *, error *)\n");
	while (signaturePtr->functor) {
		printf("    %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p6t2_multiplexer(bool * ret, StringObj *funcname, code * param0, code * param1, StringObj * param2, unsigned int * param3, error * param4) {
	struct signatures_p6t2 *signaturePtr;
	void (*functorPtr)(bool *, code *, code *, StringObj *, unsigned int *, error *);
	signaturePtr=p6t2Array;
#ifdef DEBUG
	printf("p6t2 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1,  param2,  param3,  param4);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p6t2 multiplexer undefined.\n",funcname->str);
}

#include "implementation_p6t2.c"

