/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */


#include <gdome.h>
#include <gdome-xpath.h>
#include <unistd.h>
#include <assert.h>
#include "mp_p2t1.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p2t1 type functions
 *
 */


struct signatures_p2t1 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(code *, error *);
};


/* prototypes for handling functions */

private void f77xml__di_mkref(code *, error *);
private void f77xml__debug_dumpCache(code *, error *);
private void f77xml__Cache_flush(code *, error *);
private void f77xml__xpeval_mkref(code *, error *);


private struct signatures_p2t1 p2t1Array[] = {
	{"di_mkref", &f77xml__di_mkref },
	{"debug_dumpCache", &f77xml__debug_dumpCache },
	{"Cache_flush", &f77xml__Cache_flush },
	{"xpeval_mkref", &f77xml__xpeval_mkref },
	{"", NULL }
};


void f77xml_p2t1_print() {
	struct signatures_p2t1 *signaturePtr;
	signaturePtr=p2t1Array;
	printf("p2t1 (code *, error *)\n");
	while (signaturePtr->functor) {
		printf("    %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p2t1_multiplexer(code * ret, StringObj *funcname, error * param0) {
	struct signatures_p2t1 *signaturePtr;
	void (*functorPtr)(code *, error *);
	signaturePtr=p2t1Array;
#ifdef DEBUG
	printf("p2t1 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p2t1 multiplexer undefined.\n",funcname->str);
}

#include "implementation_p2t1.c"

