/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */


#include <gdome.h>
#include <gdome-xpath.h>
#include <unistd.h>
#include <assert.h>
#include "mp_p5t7.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p5t7 type functions
 *
 */


struct signatures_p5t7 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(code *, code *, code *, bool *, error *);
};


/* prototypes for handling functions */

private void f77xml__doc_importNode(code *, code *, code *, bool *, error *);


private struct signatures_p5t7 p5t7Array[] = {
	{"doc_importNode", &f77xml__doc_importNode },
	{"", NULL }
};


void f77xml_p5t7_print() {
	struct signatures_p5t7 *signaturePtr;
	signaturePtr=p5t7Array;
	printf("p5t7 (code *, code *, code *, bool *, error *)\n");
	while (signaturePtr->functor) {
		printf("    %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p5t7_multiplexer(code * ret, StringObj *funcname, code * param0, code * param1, bool * param2, error * param3) {
	struct signatures_p5t7 *signaturePtr;
	void (*functorPtr)(code *, code *, code *, bool *, error *);
	signaturePtr=p5t7Array;
#ifdef DEBUG
	printf("p5t7 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1,  param2,  param3);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p5t7 multiplexer undefined.\n",funcname->str);
}

#include "implementation_p5t7.c"

