/* automatically generated by APIGen */

#include "stringobj.h"
#include "defines.h"

void f77xml_p6t1_print();
void f77xml_p6t1_multiplexer(code *, StringObj *, code *, code *, code *, code *, error *);
