/* automatically generated by APIGen */

#include "stringobj.h"
#include "defines.h"

void f77xml_p5t6_print();
void f77xml_p5t6_multiplexer(code *, StringObj *, code *, unsigned int *, code *, error *);
