/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */


#include <gdome.h>
#include <gdome-xpath.h>
#include <unistd.h>
#include <assert.h>
#include "mp_p8t1.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p8t1 type functions
 *
 */


struct signatures_p8t1 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(code *, code *, code *, code *, code *, unsigned int *, code *, error *);
};


/* prototypes for handling functions */

private void f77xml__xpeval_evaluate(code *, code *, code *, code *, code *, unsigned int *, code *, error *);


private struct signatures_p8t1 p8t1Array[] = {
	{"xpeval_evaluate", &f77xml__xpeval_evaluate },
	{"", NULL }
};


void f77xml_p8t1_print() {
	struct signatures_p8t1 *signaturePtr;
	signaturePtr=p8t1Array;
	printf("p8t1 (code *, code *, code *, code *, code *, unsigned int *, code *, error *)\n");
	while (signaturePtr->functor) {
		printf("    %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p8t1_multiplexer(code * ret, StringObj *funcname, code * param0, code * param1, code * param2, code * param3, unsigned int * param4, code * param5, error * param6) {
	struct signatures_p8t1 *signaturePtr;
	void (*functorPtr)(code *, code *, code *, code *, code *, unsigned int *, code *, error *);
	signaturePtr=p8t1Array;
#ifdef DEBUG
	printf("p8t1 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1,  param2,  param3,  param4,  param5,  param6);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p8t1 multiplexer undefined.\n",funcname->str);
}

#include "implementation_p8t1.c"

