/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */


#include <gdome.h>
#include <gdome-xpath.h>
#include <unistd.h>
#include <assert.h>
#include "mp_p4t5.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p4t5 type functions
 *
 */


struct signatures_p4t5 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(bool *, code *, StringObj *, error *);
};


/* prototypes for handling functions */

private void f77xml__str_equal(bool *, code *, StringObj *, error *);


private struct signatures_p4t5 p4t5Array[] = {
	{"str_equal", &f77xml__str_equal },
	{"", NULL }
};


void f77xml_p4t5_print() {
	struct signatures_p4t5 *signaturePtr;
	signaturePtr=p4t5Array;
	printf("p4t5 (bool *, code *, StringObj *, error *)\n");
	while (signaturePtr->functor) {
		printf("    %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p4t5_multiplexer(bool * ret, StringObj *funcname, code * param0, StringObj * param1, error * param2) {
	struct signatures_p4t5 *signaturePtr;
	void (*functorPtr)(bool *, code *, StringObj *, error *);
	signaturePtr=p4t5Array;
#ifdef DEBUG
	printf("p4t5 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1,  param2);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p4t5 multiplexer undefined.\n",funcname->str);
}

#include "implementation_p4t5.c"

