/* automatically generated by APIGen */

#include "stringobj.h"
#include "defines.h"

void f77xml_p6t2_print();
void f77xml_p6t2_multiplexer(bool *, StringObj *, code *, code *, StringObj *, unsigned int *, error *);
