/* Automatically generated by APIGen */
/* Changes will not survive. Modify    */
/* apigen.xml file instead                     */


#include <gdome.h>
#include <gdome-xpath.h>
#include <unistd.h>
#include <assert.h>
#include "mp_p5t2.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p5t2 type functions
 *
 */


struct signatures_p5t2 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(bool *, code *, StringObj *, unsigned int *, error *);
};


/* prototypes for handling functions */

private void f77xml__str_toFortran(bool *, code *, StringObj *, unsigned int *, error *);


private struct signatures_p5t2 p5t2Array[] = {
	{"str_toFortran", &f77xml__str_toFortran },
	{"", NULL }
};


void f77xml_p5t2_print() {
	struct signatures_p5t2 *signaturePtr;
	signaturePtr=p5t2Array;
	printf("p5t2 (bool *, code *, StringObj *, unsigned int *, error *)\n");
	while (signaturePtr->functor) {
		printf("    %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p5t2_multiplexer(bool * ret, StringObj *funcname, code * param0, StringObj * param1, unsigned int * param2, error * param3) {
	struct signatures_p5t2 *signaturePtr;
	void (*functorPtr)(bool *, code *, StringObj *, unsigned int *, error *);
	signaturePtr=p5t2Array;
#ifdef DEBUG
	printf("p5t2 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1,  param2,  param3);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p5t2 multiplexer undefined.\n",funcname->str);
}

#include "implementation_p5t2.c"

