/* Automatically generated by APIGen */
/* Changes will not survive. Modify  */
/* apigen.xml file instead           */


#include <gdome.h>
#include <unistd.h>
#include "mp_p3t3.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p3t3 type functions
 *
 */


struct signatures_p3t3 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(unsigned int *, code *, error *);
};


/* prototypes for handling functions */

private void f77xml__str_len(unsigned int *, code *, error *);
private void f77xml__nl_length(unsigned int *, code *, error *);
private void f77xml__n_nodeType(unsigned int *, code *, error *);


private struct signatures_p3t3 p3t3Array[] = {
	{"str_len", &f77xml__str_len },
	{"nl_length", &f77xml__nl_length },
	{"n_nodeType", &f77xml__n_nodeType },
	{"", NULL }
};


void f77xml_p3t3_print() {
	struct signatures_p3t3 *signaturePtr;
	signaturePtr=p3t3Array;
	printf("p3t3 (unsigned int *, code *, error *)\n");
	while (signaturePtr->functor) {
		printf("  %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p3t3_multiplexer(unsigned int * ret, string *funcname, code * param0, error * param1) {
	struct signatures_p3t3 *signaturePtr;
	void (*functorPtr)(unsigned int *, code *, error *);
	signaturePtr=p3t3Array;
#ifdef DEBUG
	printf("p3t3 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p3t3 multiplexer undefined.\n",funcname->str);
}



#include "interface_p3t3.c"

