/* Automatically generated by APIGen */
/* Changes will not survive. Modify  */
/* apigen.xml file instead           */


#include <gdome.h>
#include <unistd.h>
#include "mp_p4t2.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p4t2 type functions
 *
 */


struct signatures_p4t2 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(code *, code *, unsigned int *, error *);
};


/* prototypes for handling functions */

private void f77xml__nl_item(code *, code *, unsigned int *, error *);


private struct signatures_p4t2 p4t2Array[] = {
	{"nl_item", &f77xml__nl_item },
	{"", NULL }
};


void f77xml_p4t2_print() {
	struct signatures_p4t2 *signaturePtr;
	signaturePtr=p4t2Array;
	printf("p4t2 (code *, code *, unsigned int *, error *)\n");
	while (signaturePtr->functor) {
		printf("  %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p4t2_multiplexer(code * ret, string *funcname, code * param0, unsigned int * param1, error * param2) {
	struct signatures_p4t2 *signaturePtr;
	void (*functorPtr)(code *, code *, unsigned int *, error *);
	signaturePtr=p4t2Array;
#ifdef DEBUG
	printf("p4t2 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1,  param2);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p4t2 multiplexer undefined.\n",funcname->str);
}



#include "interface_p4t2.c"

