/* Automatically generated by APIGen */
/* Changes will not survive. Modify  */
/* apigen.xml file instead           */


#include <gdome.h>
#include <unistd.h>
#include "mp_p4t1.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p4t1 type functions
 *
 */


struct signatures_p4t1 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(code *, code *, code *, error *);
};


/* prototypes for handling functions */

private void f77xml__dom_saveDocToFile(code *, code *, code *, error *);
private void f77xml__doc_createElement(code *, code *, code *, error *);
private void f77xml__doc_createTextNode(code *, code *, code *, error *);
private void f77xml__doc_createComment(code *, code *, code *, error *);
private void f77xml__el_appendChild(code *, code *, code *, error *);


private struct signatures_p4t1 p4t1Array[] = {
	{"dom_saveDocToFile", &f77xml__dom_saveDocToFile },
	{"doc_createElement", &f77xml__doc_createElement },
	{"doc_createTextNode", &f77xml__doc_createTextNode },
	{"doc_createComment", &f77xml__doc_createComment },
	{"el_appendChild", &f77xml__el_appendChild },
	{"", NULL }
};


void f77xml_p4t1_print() {
	struct signatures_p4t1 *signaturePtr;
	signaturePtr=p4t1Array;
	printf("p4t1 (code *, code *, code *, error *)\n");
	while (signaturePtr->functor) {
		printf("  %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p4t1_multiplexer(code * ret, string *funcname, code * param0, code * param1, error * param2) {
	struct signatures_p4t1 *signaturePtr;
	void (*functorPtr)(code *, code *, code *, error *);
	signaturePtr=p4t1Array;
#ifdef DEBUG
	printf("p4t1 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1,  param2);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p4t1 multiplexer undefined.\n",funcname->str);
}



#include "interface_p4t1.c"

