/* Automatically generated by APIGen */
/* Changes will not survive. Modify  */
/* apigen.xml file instead           */


#include <gdome.h>
#include <unistd.h>
#include "mp_p3t1.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p3t1 type functions
 *
 */


struct signatures_p3t1 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(code *, code *, error *);
};


/* prototypes for handling functions */

private void f77xml__doc_documentElement(code *, code *, error *);
private void f77xml__el_firstChild(code *, code *, error *);
private void f77xml__el_lastChild(code *, code *, error *);
private void f77xml__el_nextSibling(code *, code *, error *);
private void f77xml__el_previousSibling(code *, code *, error *);
private void f77xml__el_parentNode(code *, code *, error *);
private void f77xml__el_childNodes(code *, code *, error *);
private void f77xml__dom_createDocFromURI(code *, code *, error *);
private void f77xml__el_tagName(code *, code *, error *);


private struct signatures_p3t1 p3t1Array[] = {
	{"doc_documentElement", &f77xml__doc_documentElement },
	{"el_firstChild", &f77xml__el_firstChild },
	{"el_lastChild", &f77xml__el_lastChild },
	{"el_nextSibling", &f77xml__el_nextSibling },
	{"el_previousSibling", &f77xml__el_previousSibling },
	{"el_parentNode", &f77xml__el_parentNode },
	{"el_childNodes", &f77xml__el_childNodes },
	{"dom_createDocFromURI", &f77xml__dom_createDocFromURI },
	{"el_tagName", &f77xml__el_tagName },
	{"", NULL }
};


void f77xml_p3t1_print() {
	struct signatures_p3t1 *signaturePtr;
	signaturePtr=p3t1Array;
	printf("p3t1 (code *, code *, error *)\n");
	while (signaturePtr->functor) {
		printf("  %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p3t1_multiplexer(code * ret, string *funcname, code * param0, error * param1) {
	struct signatures_p3t1 *signaturePtr;
	void (*functorPtr)(code *, code *, error *);
	signaturePtr=p3t1Array;
#ifdef DEBUG
	printf("p3t1 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p3t1 multiplexer undefined.\n",funcname->str);
}



#include "interface_p3t1.c"

