/* automatically generated by APIGen */

#include "stringobject.h"
#include "defines.h"

void f77xml_p5t2_print();
void f77xml_p5t2_multiplexer(bool *, string *, code *, string *, unsigned int *, error *);
