/* Automatically generated by APIGen */
/* Changes will not survive. Modify  */
/* apigen.xml file instead           */


#include <gdome.h>
#include <unistd.h>
#include "mp_p5t1.h"
#include "cache.h"
#include "defines.h"
#include "domimpl.h"
#include "error.h"


/*
 * multiplexer definition for p5t1 type functions
 *
 */


struct signatures_p5t1 {
	char funcname[FUNCTION_NAME_MAX_LEN];
	void (*functor)(code *, code *, code *, code *, error *);
};


/* prototypes for handling functions */

private void f77xml__el_setAttribute(code *, code *, code *, code *, error *);


private struct signatures_p5t1 p5t1Array[] = {
	{"el_setAttribute", &f77xml__el_setAttribute },
	{"", NULL }
};


void f77xml_p5t1_print() {
	struct signatures_p5t1 *signaturePtr;
	signaturePtr=p5t1Array;
	printf("p5t1 (code *, code *, code *, code *, error *)\n");
	while (signaturePtr->functor) {
		printf("  %s\n",signaturePtr->funcname);
		signaturePtr++;
	}
}


void f77xml_p5t1_multiplexer(code * ret, string *funcname, code * param0, code * param1, code * param2, error * param3) {
	struct signatures_p5t1 *signaturePtr;
	void (*functorPtr)(code *, code *, code *, code *, error *);
	signaturePtr=p5t1Array;
#ifdef DEBUG
	printf("p5t1 multiplexer: %s\n",funcname->str);
#endif


	while (signaturePtr->functor) {
		if (!strcmp(funcname->str,signaturePtr->funcname)) {
			functorPtr=signaturePtr->functor;
			(*functorPtr)(ret,  param0,  param1,  param2,  param3);

			return;
		}
		signaturePtr++;
	}


	printf("Function %s for p5t1 multiplexer undefined.\n",funcname->str);
}



#include "interface_p5t1.c"

